name: xml_parser
description: An unopinionated XML parser that can read, traverse, modify, and write XML documents.
version: 1.1.0
homepage: https://github.com/james-alex/xml_parser

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.19.1
  html_character_entities: ^1.0.0+1
  http: ^1.1.0
  recursive_regex: ^1.0.0
  meta: ^1.16.0

dev_dependencies:
  test: ^1.17.4
  lints: ^5.0.0
